blog/urls.py
from django.conf.urls import url
from blog import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^article/(?P<article_id>\d+)$', views.ArticleDetailView.as_view(), name='detail'),
    url(r'^category/(?P<cate_id>\d+)$', views.CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<tag_id>\d+)$', views.TagView.as_view(), name='tag'),
    url(r'^archive/(?P<year>\d+)/(?P<month>\d+)$', views.ArchiveView.as_view(), name='archive'),
    # url(r'^article/(?P<article_id>\d+)/comment/$', views.CommentPostView.as_view(), name='comment'),
    url(r'^article/(?P<article_id>\d+)/like/$', views.article_like, name='like'),
]

smallsite/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.views.static import serve

from smallsite import settings

urlpatterns = [
    url(r'^trial/', include('trial.urls', namespace='trial', app_name='trial')),
    url(r'^', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT},
        name="media"),
]


if settings.BACKEND_SERVER:
    urlpatterns += [
        url(r'^backend/', include(admin.site.urls)),
    ]

blog/models.py
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from django.db import models
from django.core.urlresolvers import reverse
from collections import defaultdict
from crum import get_current_request

class ArticleManage(models.Manager):
    def archive(self):
        date_list = Article.objects.datetimes('ctime', 'month', order='DESC')
        date_dict = defaultdict(list)
        for d in date_list:
            date_dict[d.year].append(d.month)
        return sorted(date_dict.items(), reverse=True)  # 模板不支持defaultdict


class Article(models.Model):
    STATUS_CHOICES = (
        (False, '草稿'),
        (True, '发布'),
    )
    AUTHORITY_CHOICES = (
        (0, '全员可见'),
        (1, '仅登录可见')
    )
    title = models.CharField('标题', max_length=200)
    author = models.ForeignKey(User, verbose_name="作者", blank=True, null=True,
                               help_text="不填默认为当前用户")
    picture = models.FileField("预览图片", upload_to="blog/img", blank=True, null=True)
    abstract = models.CharField('摘要', max_length=54, blank=True, null=True)
    content = RichTextField('正文')
    status = models.BooleanField('文章状态', default=False, choices=STATUS_CHOICES)
    user_auth = models.SmallIntegerField('阅读权限', default=0,
                                         choices=AUTHORITY_CHOICES)
    views = models.PositiveIntegerField('浏览量', default=0)
    likes = models.PositiveIntegerField('点赞数', default=0)
    topped = models.BooleanField('置顶', default=False)
    category = models.ForeignKey('Category', verbose_name='分类', null=True, on_delete=models.SET_NULL)
    tags = models.ManyToManyField('Tag', verbose_name='标签集合', blank=True)
    ctime = models.DateTimeField("创建时间", auto_now_add=True)
    utime = models.DateTimeField("更新时间", auto_now=True)

    objects = ArticleManage()

    class Meta:
        verbose_name = "文章"
        verbose_name_plural = "文章"
        ordering = ("-id",)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'article_id': self.pk})

    def get_picture_url(self):
        return reverse('media', kwargs={'path': self.picture})

    # def save(self, from_web=False, *args, **kwargs):
    #     if not from_web:
    #         request = get_current_request()
    #         self.author = request.user
    #     super(Article, self).save(*args, **kwargs)


class Category(models.Model):
    name = models.CharField('类名', max_length=20)
    ctime = models.DateTimeField("创建时间", auto_now_add=True)
    utime = models.DateTimeField("更新时间", auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "分类"
        verbose_name_plural = "分类"


class Tag(models.Model):
    name = models.CharField('标签名', max_length=20)
    ctime = models.DateTimeField("创建时间", auto_now_add=True)
    utime = models.DateTimeField("更新时间", auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "标签"
        verbose_name_plural = "标签"

blog/forms.py
from django import forms
from .models import Article, Tag
from django.contrib.admin.widgets import FilteredSelectMultiple


class ArticleAdminForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
            queryset=Tag.objects.all(),
            required=False,
            widget=FilteredSelectMultiple(verbose_name='标签', is_stacked=False))

    class Meta:
        model = Article
        exclude = ("author", "views", "likes","ctime", "utime")

    def __init__(self, *args, **kwargs):
        super(ArticleAdminForm, self).__init__(*args, **kwargs)

        if self.instance and self.instance.pk:
            self.fields['tags'].initial = self.instance.tags.all()

    def save(self, commit=True):
        result = super(ArticleAdminForm, self).save(commit=False)
        if commit:
            result.save()
        if result.pk:
            result.tags = self.cleaned_data['tags']
            self.save_m2m()
        return result

blog/views.py
from django.core.urlresolvers import reverse
from django.shortcuts import HttpResponseRedirect
from django.views.generic import TemplateView
from django.views.generic import View
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from blog.models import Article, Category, Tag


# Create your views here.
class IndexView(ListView):
    template_name = "blog/index.html"
    context_object_name = "article_list"

    def get_queryset(self):
        if self.request.user.is_authenticated():
            user_auth = 1
        else:
            user_auth = 0
        search_key = self.request.GET.get("search")
        if search_key:
            part_1 = Article.objects.filter(title__contains=search_key,
                                            status=True, user_auth__lte=user_auth)
            part_2 = Article.objects.filter(abstract__contains=search_key,
                                            status=True, user_auth__lte=user_auth)
            part_3 = Article.objects.filter(content__contains=search_key,
                                            status=True, user_auth__lte=user_auth)
            article_list = list(part_1) + list(part_2) + list(part_3)
        else:
            article_list = Article.objects.filter(status=True,
                                                  user_auth__lte=user_auth)
        return article_list

    def get_context_data(self, **kwargs):
        kwargs['category_list'] = Category.objects.all().order_by('name')
        kwargs['date_archive'] = Article.objects.archive()
        kwargs['tag_list'] = Tag.objects.all().order_by('name')
        return super(IndexView, self).get_context_data(**kwargs)


class ArticleDetailView(DetailView):
    model = Article
    template_name = "blog/detail.html"
    context_object_name = "article"
    pk_url_kwarg = 'article_id'

    def get_object(self, queryset=None):
        article_obj = super(ArticleDetailView, self).get_object()
        article_obj.views += 1
        article_obj.save()
        return article_obj

    def get_context_data(self, **kwargs):
        kwargs['category_list'] = Category.objects.all().order_by('name')
        kwargs['date_archive'] = Article.objects.archive()
        kwargs['tag_list'] = Tag.objects.all().order_by('name')
        return super(ArticleDetailView, self).get_context_data(**kwargs)


class CategoryView(ListView):
    template_name = "blog/index.html"
    context_object_name = "article_list"

    def get_queryset(self):
        article_list = Article.objects.filter(category=self.kwargs['cate_id'], status=True)
        return article_list

    def get_context_data(self, **kwargs):
        kwargs['category_list'] = Category.objects.all().order_by('name')
        kwargs['date_archive'] = Article.objects.archive()
        kwargs['tag_list'] = Tag.objects.all().order_by('name')
        return super(CategoryView, self).get_context_data(**kwargs)


class TagView(ListView):
    template_name = "blog/index.html"
    context_object_name = "article_list"

    def get_queryset(self):
        article_list = Article.objects.filter(tags=self.kwargs['tag_id'], status=True)
        return article_list

    def get_context_data(self, **kwargs):
        kwargs['category_list'] = Category.objects.all().order_by('name')
        kwargs['date_archive'] = Article.objects.archive()
        kwargs['tag_list'] = Tag.objects.all().order_by('name')
        return super(TagView, self).get_context_data(**kwargs)


class ArchiveView(ListView):
    template_name = "blog/index.html"
    context_object_name = "article_list"

    def get_queryset(self):
        year = int(self.kwargs['year'])
        month = int(self.kwargs['month'])
        article_list = Article.objects.filter(ctime__year=year, ctime__month=month)
        return article_list

    def get_context_data(self, **kwargs):
        kwargs['category_list'] = Category.objects.all().order_by('name')
        kwargs['date_archive'] = Article.objects.archive()
        kwargs['tag_list'] = Tag.objects.all().order_by('name')
        return super(ArchiveView, self).get_context_data(**kwargs)


def article_like(request, article_id):
    article_obj = Article.objects.get(id=article_id)
    article_obj.likes += 1
    article_obj.save()
    redirect_uri = reverse('blog:detail', kwargs={'article_id': article_id})
    return HttpResponseRedirect(redirect_uri)

blog/templates/blog/comment.html
<div class="comment">
    <div class="comment-main">
        <p class="head">评论详情</p>
        <form method="post" action="{% url 'blog:comment' article.pk %}">
            {% csrf_token %}
            <div class="row">
                {% for field in form %}
                    {{ field }}
                    {{ field.errors }}
                    <br>
                {% endfor %}
            </div>
            <button type="submit" class="com-button">评论</button>
        </form>
        <p class="comment-count">共{{ 0 }}条评论</p>
        <hr>
        {% for comment in comment_list %}
            <div class="main-content">
{#                <img src="月英1.jpg" class="user-avatar">#}
                <span class="user-nickname">{{ comment.user_name }}</span>
                <time class="time">{{ comment.ctime }}</time>
                <div class="comment-content">
                    {{ comment.body }}
                </div>
{#                <a href="">回复</a>#}
            </div>
            <hr>
        {% endfor %}
    </div>
</div>

blog/templates/blog/detail.html
{% extends 'base.html' %}
{% block content %}

<div class="blog"><!-- start main -->
	<div class="container">
		<div class="main row">
            <div class="col-md-8">
                <h2 class="style">{{ article.title }}</h2>
                <div class="blog_list pull-left">
                    <ul class="list-unstyled">
                        <li><i class="fa fa-calendar-o"></i><span>{{ article.utime|date:"Y年n月d日" }}</span></li>
                        <li><i class="fa fa-user"></i><span>{{ article.author.username|default:'admin' }}</span></li>
                        <li><i class="fa fa-eye"></i><span>{{  article.views }}</span></li>
                    </ul>
                </div>
                <div class="b_left pull-right">
                    <a href="{% url 'blog:like' article.pk %}"><i class="fa fa-heart"></i><span> {{ article.likes }} </span></a>
                </div>
                <div class="clearfix"></div>
                {% if article.picture %}
                <div class="details row">
                    <div class="col-md-4">
                        <img src="{{ article.get_picture_url }}" alt="" class="img-responsive"/>
                    </div>
                    <div class="col-md-4">
                        <p>{{ article.abstract }}</p>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="clearfix"></div>
                {% endif %}
                <p class="para">{{ article.content |safe }}</p>
                {% include 'blog/duoshuo.html' %}
            </div>
            <div class="col-md-4 blog_right">
                {% include 'blog/sidebar.html' %}
            </div>
		</div>
	</div>
</div><!-- end main -->
            
{% endblock %}

blog/templates/blog/duoshuo.html
<!-- 多说评论框 start -->
	<div class="ds-thread" data-thread-key="{{ article.pk }}" data-title="{{ article.title }}" data-url="{{ article.get_absolute_url }}"></div>
<!-- 多说评论框 end -->
<!-- 多说公共JS代码 start (一个网页只需插入一次) -->
<script type="text/javascript">
var duoshuoQuery = {short_name:"smallsite"};
	(function() {
		var ds = document.createElement('script');
		ds.type = 'text/javascript';ds.async = true;
		ds.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') + '//static.duoshuo.com/embed.js';
		ds.charset = 'UTF-8';
		(document.getElementsByTagName('head')[0]
		 || document.getElementsByTagName('body')[0]).appendChild(ds);
	})();
	</script>
<!-- 多说公共JS代码 end -->

blog/templates/blog/index.html
{% extends 'base.html' %}
{% block content %}
<div class="blog"><!-- start main -->
	<div class="container">
		<div class="main row">
			<div class="col-md-8 blog_left">
				<h2 class="style">我的博客</h2>
                {% load paginate_tags %}
                {% paginate article_list 5 %}
                {% for article in article_list %}
                <div class="blog_main">
                    <h4><a href="{% url 'blog:detail' article.pk %}">{{ article.title }}</a></h4>
                    {% if article.picture %}
                        <a href="{% url 'blog:detail' article.pk %}"><img src="{{article.get_picture_url}}" alt="" class="blog_img img-responsive"/></a>
                    {% endif %}
                    <div class="blog_list pull-left">
                          <ul class="list-unstyled">
                            <li><i class="fa fa-calendar-o"></i><span>{{ article.utime|date:"Y年n月d日" }}</span></li>
                            <li><i class="fa fa-user"></i><span>{{ article.author.username|default:'admin' }}</span></li>
                            <li><i class="fa fa-eye"></i><span>{{  article.views }}</span></li>
                          </ul>
                    </div>
                    <div class="b_left pull-right">
                        <a href="{% url 'blog:like' article.pk %}"><i class="fa fa-heart"></i><span> {{ article.likes }} </span></a>
                    </div>
                    <div class="clearfix"></div>
                    <p class="para"> &nbsp;&nbsp;&nbsp;&nbsp;{{ article.abstract }} </p>
                    <div class="read_more btm">
                        <a href="{% url 'blog:detail' article.id %}">阅读全文>></a>
                    </div>
                </div>
                {% endfor %}
                {% include 'blog/pagination.html' %}
            </div>
            <div class="col-md-4 blog_right">
                {% include 'blog/sidebar.html' %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/pagination.html
<nav>
  <ul class="pagination pagination-lg blog_pagination">
    {% if article_list.has_previous %}
        <li>
            <a class="previous-page" aria-label="Previous" href="?page={{ article_list.previous_page_number }}">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
    {% endif %}

    {% if first_page == current_page %}
        <li class="active disabled"><span>1</span></li>
    {% else %}
        <li><a href="?page=1" class="first-page">1</a>
    {% endif %}

    {% if pages_first > 2 %}
        <li><span>...</span></li>
    {% endif %}

    {% for page in pages %}
        {% if page == current_page %}
            <li class="active"><span>{{ page }}</span></li>
        {% else %}
            <li><a href="?page={{ page }}">{{ page }}</a></li>
        {% endif %}
    {% endfor %}

    {% if pages_last < last_page %}
        <li><span>...</span></li>
    {% endif %}

    {% if last_page != 1 %}
        {% if last_page == current_page %}
            <li class="active"><span>{{ last_page }}</span></li>
        {% else %}
            <li><a href="?page={{ last_page }}">{{ last_page }}</a></li>
        {% endif %}
    {% endif %}

    {% if article_list.has_next %}
        <li>
        <a href="?page={{ article_list.next_page_number }}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
        </a>
        </li>
    {% endif %}
  </ul>
</nav>

blog/templates/blog/sidebar.html
<ul class="ads_nav list-unstyled">
    <h4>特别感谢</h4>
    {#125 x 125#}
    <li><a href="https://www.verycloud.cn/" target="_blank"><img src="/static/blog/img/verycloud_logo.png" alt=""> </a></li>
{#    <li><a href="#"><img src="" alt=""> </a></li>#}
{#    <li><a href="#"><img src="" alt=""> </a></li>#}
{#    <li><a href="#"><img src="" alt=""> </a></li>#}
{#    css --> .ads_nav li a img#}
    <div class="clearfix"></div>
</ul>

<form class="form-inline" method="get" action="/?search=search">
<input type="text" class="form-control input-lg btn-block" name="search" placeholder="标题->简介->内容">
<button type="submit" class="btn btn-success btn-lg">搜索</button>
</form>

<ul class="tag_nav list-unstyled">
    <h4>分类</h4>
    <div class="list-group">
        {% for category in category_list %}
            <li class="active"><a href="{% url 'blog:category' category.pk %}">{{ category.name }}</a></li>
        {% endfor %}
    </div>
    <div class="clearfix"></div>
    <h4>标签</h4>
    <div class="list-group">
        {% for tag in tag_list %}
            <li class="active"><a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a></li>
        {% endfor %}
    </div>
    <div class="clearfix"></div>
    <h4>文章归档：</h4>
    <div class="list-group">
        {% for year,months in date_archive %}
            {% for month in months %}
                <li class="active"><a href="{% url 'blog:archive' year month %}">{{ year }}-{{ month }}</a></li>
            {% endfor %}
        {% endfor %}
    </div>
</ul>